/* automatically generated by rust-bindgen 0.72.1 */

pub type UNUM8 = u8;
pub type UNUM16 = u16;
pub type SNUM32 = i32;
pub type UNUM32 = u32;
pub type CHAR8 = ::std::os::raw::c_char;
impl E_PDU_PC {
    pub const PDU_PC_TIMING: E_PDU_PC = E_PDU_PC(1);
    pub const PDU_PC_INIT: E_PDU_PC = E_PDU_PC(2);
    pub const PDU_PC_COM: E_PDU_PC = E_PDU_PC(3);
    pub const PDU_PC_ERRHDL: E_PDU_PC = E_PDU_PC(4);
    pub const PDU_PC_BUSTYPE: E_PDU_PC = E_PDU_PC(5);
    pub const PDU_PC_UNIQUE_ID: E_PDU_PC = E_PDU_PC(6);
    pub const PDU_PC_TESTER_PRESENT: E_PDU_PC = E_PDU_PC(7);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_PC(pub ::std::os::raw::c_uint);
pub use self::E_PDU_PC as T_PDU_PC;
impl E_PDU_PT {
    pub const PDU_PT_UNUM8: E_PDU_PT = E_PDU_PT(257);
    pub const PDU_PT_SNUM8: E_PDU_PT = E_PDU_PT(258);
    pub const PDU_PT_UNUM16: E_PDU_PT = E_PDU_PT(259);
    pub const PDU_PT_SNUM16: E_PDU_PT = E_PDU_PT(260);
    pub const PDU_PT_UNUM32: E_PDU_PT = E_PDU_PT(261);
    pub const PDU_PT_SNUM32: E_PDU_PT = E_PDU_PT(262);
    pub const PDU_PT_BYTEFIELD: E_PDU_PT = E_PDU_PT(263);
    pub const PDU_PT_STRUCTFIELD: E_PDU_PT = E_PDU_PT(264);
    pub const PDU_PT_LONGFIELD: E_PDU_PT = E_PDU_PT(265);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_PT(pub ::std::os::raw::c_uint);
pub use self::E_PDU_PT as T_PDU_PT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_PARAM_BYTEFIELD_DATA {
    pub ParamMaxLen: UNUM32,
    pub ParamActLen: UNUM32,
    pub pDataArray: *mut UNUM8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_PARAM_BYTEFIELD_DATA"]
        [::std::mem::size_of::<PDU_PARAM_BYTEFIELD_DATA>() - 16usize];
    ["Alignment of PDU_PARAM_BYTEFIELD_DATA"]
        [::std::mem::align_of::<PDU_PARAM_BYTEFIELD_DATA>() - 8usize];
    ["Offset of field: PDU_PARAM_BYTEFIELD_DATA::ParamMaxLen"]
        [::std::mem::offset_of!(PDU_PARAM_BYTEFIELD_DATA, ParamMaxLen) - 0usize];
    ["Offset of field: PDU_PARAM_BYTEFIELD_DATA::ParamActLen"]
        [::std::mem::offset_of!(PDU_PARAM_BYTEFIELD_DATA, ParamActLen) - 4usize];
    ["Offset of field: PDU_PARAM_BYTEFIELD_DATA::pDataArray"]
        [::std::mem::offset_of!(PDU_PARAM_BYTEFIELD_DATA, pDataArray) - 8usize];
};
impl E_PDU_CPST {
    pub const PDU_CPST_SESSION_TIMING: E_PDU_CPST = E_PDU_CPST(1);
    pub const PDU_CPST_ACCESS_TIMING: E_PDU_CPST = E_PDU_CPST(2);
    pub const PDU_CPST_TLS_VERSION_AND_CIPHER: E_PDU_CPST = E_PDU_CPST(3);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_CPST(pub ::std::os::raw::c_uint);
pub use self::E_PDU_CPST as T_PDU_CPST;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_PARAM_STRUCTFIELD_DATA {
    pub ComParamStructType: T_PDU_CPST,
    pub ParamMaxEntries: UNUM32,
    pub ParamActEntries: UNUM32,
    pub pStructArray: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_PARAM_STRUCTFIELD_DATA"]
        [::std::mem::size_of::<PDU_PARAM_STRUCTFIELD_DATA>() - 24usize];
    ["Alignment of PDU_PARAM_STRUCTFIELD_DATA"]
        [::std::mem::align_of::<PDU_PARAM_STRUCTFIELD_DATA>() - 8usize];
    ["Offset of field: PDU_PARAM_STRUCTFIELD_DATA::ComParamStructType"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCTFIELD_DATA, ComParamStructType) - 0usize];
    ["Offset of field: PDU_PARAM_STRUCTFIELD_DATA::ParamMaxEntries"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCTFIELD_DATA, ParamMaxEntries) - 4usize];
    ["Offset of field: PDU_PARAM_STRUCTFIELD_DATA::ParamActEntries"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCTFIELD_DATA, ParamActEntries) - 8usize];
    ["Offset of field: PDU_PARAM_STRUCTFIELD_DATA::pStructArray"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCTFIELD_DATA, pStructArray) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_PARAM_STRUCT_SESS_TIMING {
    pub session: UNUM16,
    pub P2Max_high: UNUM8,
    pub P2Max_low: UNUM8,
    pub P2Star_high: UNUM8,
    pub P2Star_low: UNUM8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_PARAM_STRUCT_SESS_TIMING"]
        [::std::mem::size_of::<PDU_PARAM_STRUCT_SESS_TIMING>() - 6usize];
    ["Alignment of PDU_PARAM_STRUCT_SESS_TIMING"]
        [::std::mem::align_of::<PDU_PARAM_STRUCT_SESS_TIMING>() - 2usize];
    ["Offset of field: PDU_PARAM_STRUCT_SESS_TIMING::session"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_SESS_TIMING, session) - 0usize];
    ["Offset of field: PDU_PARAM_STRUCT_SESS_TIMING::P2Max_high"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_SESS_TIMING, P2Max_high) - 2usize];
    ["Offset of field: PDU_PARAM_STRUCT_SESS_TIMING::P2Max_low"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_SESS_TIMING, P2Max_low) - 3usize];
    ["Offset of field: PDU_PARAM_STRUCT_SESS_TIMING::P2Star_high"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_SESS_TIMING, P2Star_high) - 4usize];
    ["Offset of field: PDU_PARAM_STRUCT_SESS_TIMING::P2Star_low"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_SESS_TIMING, P2Star_low) - 5usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_PARAM_STRUCT_ACCESS_TIMING {
    pub P2Min: UNUM8,
    pub P2Max: UNUM8,
    pub P3Min: UNUM8,
    pub P3Max: UNUM8,
    pub P4Min: UNUM8,
    pub TimingSet: UNUM8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_PARAM_STRUCT_ACCESS_TIMING"]
        [::std::mem::size_of::<PDU_PARAM_STRUCT_ACCESS_TIMING>() - 6usize];
    ["Alignment of PDU_PARAM_STRUCT_ACCESS_TIMING"]
        [::std::mem::align_of::<PDU_PARAM_STRUCT_ACCESS_TIMING>() - 1usize];
    ["Offset of field: PDU_PARAM_STRUCT_ACCESS_TIMING::P2Min"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_ACCESS_TIMING, P2Min) - 0usize];
    ["Offset of field: PDU_PARAM_STRUCT_ACCESS_TIMING::P2Max"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_ACCESS_TIMING, P2Max) - 1usize];
    ["Offset of field: PDU_PARAM_STRUCT_ACCESS_TIMING::P3Min"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_ACCESS_TIMING, P3Min) - 2usize];
    ["Offset of field: PDU_PARAM_STRUCT_ACCESS_TIMING::P3Max"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_ACCESS_TIMING, P3Max) - 3usize];
    ["Offset of field: PDU_PARAM_STRUCT_ACCESS_TIMING::P4Min"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_ACCESS_TIMING, P4Min) - 4usize];
    ["Offset of field: PDU_PARAM_STRUCT_ACCESS_TIMING::TimingSet"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_ACCESS_TIMING, TimingSet) - 5usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER {
    pub TlsMajorVersion: UNUM8,
    pub TlsMinorVersion: UNUM8,
    pub CipherActEntries: UNUM8,
    pub CipherList: [UNUM16; 5usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER"]
        [::std::mem::size_of::<PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER>() - 14usize];
    ["Alignment of PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER"]
        [::std::mem::align_of::<PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER>() - 2usize];
    ["Offset of field: PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER::TlsMajorVersion"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER, TlsMajorVersion) - 0usize];
    ["Offset of field: PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER::TlsMinorVersion"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER, TlsMinorVersion) - 1usize];
    ["Offset of field: PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER::CipherActEntries"][::std::mem::offset_of!(
        PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER,
        CipherActEntries
    ) - 2usize];
    ["Offset of field: PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER::CipherList"]
        [::std::mem::offset_of!(PDU_PARAM_STRUCT_TLS_VERSION_AND_CIPHER, CipherList) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_PARAM_LONGFIELD_DATA {
    pub ParamMaxLen: UNUM32,
    pub ParamActLen: UNUM32,
    pub pDataArray: *mut UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_PARAM_LONGFIELD_DATA"]
        [::std::mem::size_of::<PDU_PARAM_LONGFIELD_DATA>() - 16usize];
    ["Alignment of PDU_PARAM_LONGFIELD_DATA"]
        [::std::mem::align_of::<PDU_PARAM_LONGFIELD_DATA>() - 8usize];
    ["Offset of field: PDU_PARAM_LONGFIELD_DATA::ParamMaxLen"]
        [::std::mem::offset_of!(PDU_PARAM_LONGFIELD_DATA, ParamMaxLen) - 0usize];
    ["Offset of field: PDU_PARAM_LONGFIELD_DATA::ParamActLen"]
        [::std::mem::offset_of!(PDU_PARAM_LONGFIELD_DATA, ParamActLen) - 4usize];
    ["Offset of field: PDU_PARAM_LONGFIELD_DATA::pDataArray"]
        [::std::mem::offset_of!(PDU_PARAM_LONGFIELD_DATA, pDataArray) - 8usize];
};
impl E_PDU_IT {
    pub const PDU_IT_IO_UNUM32: E_PDU_IT = E_PDU_IT(4096);
    pub const PDU_IT_IO_PROG_VOLTAGE: E_PDU_IT = E_PDU_IT(4097);
    pub const PDU_IT_IO_BYTEARRAY: E_PDU_IT = E_PDU_IT(4098);
    pub const PDU_IT_IO_FILTER: E_PDU_IT = E_PDU_IT(4099);
    pub const PDU_IT_IO_EVENT_QUEUE_PROPERTY: E_PDU_IT = E_PDU_IT(4100);
    pub const PDU_IT_IO_TLS_CERTIFICATE: E_PDU_IT = E_PDU_IT(4101);
    pub const PDU_IT_RSC_STATUS: E_PDU_IT = E_PDU_IT(4352);
    pub const PDU_IT_PARAM: E_PDU_IT = E_PDU_IT(4608);
    pub const PDU_IT_RESULT: E_PDU_IT = E_PDU_IT(4864);
    pub const PDU_IT_STATUS: E_PDU_IT = E_PDU_IT(4865);
    pub const PDU_IT_ERROR: E_PDU_IT = E_PDU_IT(4866);
    pub const PDU_IT_INFO: E_PDU_IT = E_PDU_IT(4867);
    pub const PDU_IT_RSC_ID: E_PDU_IT = E_PDU_IT(5120);
    pub const PDU_IT_RSC_CONFLICT: E_PDU_IT = E_PDU_IT(5376);
    pub const PDU_IT_MODULE_ID: E_PDU_IT = E_PDU_IT(5632);
    pub const PDU_IT_UNIQUE_RESP_ID_TABLE: E_PDU_IT = E_PDU_IT(5888);
    pub const PDU_IT_IO_VEHICLE_ID_REQUEST: E_PDU_IT = E_PDU_IT(6144);
    pub const PDU_IT_IO_ETH_SWITCH_STATE: E_PDU_IT = E_PDU_IT(6145);
    pub const PDU_IT_IO_ENTITY_ADDRESS: E_PDU_IT = E_PDU_IT(6146);
    pub const PDU_IT_IO_ENTITY_STATUS: E_PDU_IT = E_PDU_IT(6147);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_IT(pub ::std::os::raw::c_uint);
pub use self::E_PDU_IT as T_PDU_IT;
impl E_PDU_COPT {
    pub const PDU_COPT_STARTCOMM: E_PDU_COPT = E_PDU_COPT(32769);
    pub const PDU_COPT_STOPCOMM: E_PDU_COPT = E_PDU_COPT(32770);
    pub const PDU_COPT_UPDATEPARAM: E_PDU_COPT = E_PDU_COPT(32771);
    pub const PDU_COPT_SENDRECV: E_PDU_COPT = E_PDU_COPT(32772);
    pub const PDU_COPT_DELAY: E_PDU_COPT = E_PDU_COPT(32773);
    pub const PDU_COPT_RESTORE_PARAM: E_PDU_COPT = E_PDU_COPT(32774);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_COPT(pub ::std::os::raw::c_uint);
pub use self::E_PDU_COPT as T_PDU_COPT;
impl E_PDU_OBJT {
    pub const PDU_OBJT_PROTOCOL: E_PDU_OBJT = E_PDU_OBJT(32801);
    pub const PDU_OBJT_BUSTYPE: E_PDU_OBJT = E_PDU_OBJT(32802);
    pub const PDU_OBJT_IO_CTRL: E_PDU_OBJT = E_PDU_OBJT(32803);
    pub const PDU_OBJT_COMPARAM: E_PDU_OBJT = E_PDU_OBJT(32804);
    pub const PDU_OBJT_PINTYPE: E_PDU_OBJT = E_PDU_OBJT(32805);
    pub const PDU_OBJT_RESOURCE: E_PDU_OBJT = E_PDU_OBJT(32806);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_OBJT(pub ::std::os::raw::c_uint);
pub use self::E_PDU_OBJT as T_PDU_OBJT;
impl E_PDU_STATUS {
    pub const PDU_COPST_IDLE: E_PDU_STATUS = E_PDU_STATUS(32784);
    pub const PDU_COPST_EXECUTING: E_PDU_STATUS = E_PDU_STATUS(32785);
    pub const PDU_COPST_FINISHED: E_PDU_STATUS = E_PDU_STATUS(32786);
    pub const PDU_COPST_CANCELLED: E_PDU_STATUS = E_PDU_STATUS(32787);
    pub const PDU_COPST_WAITING: E_PDU_STATUS = E_PDU_STATUS(32788);
    pub const PDU_CLLST_OFFLINE: E_PDU_STATUS = E_PDU_STATUS(32848);
    pub const PDU_CLLST_ONLINE: E_PDU_STATUS = E_PDU_STATUS(32849);
    pub const PDU_CLLST_COMM_STARTED: E_PDU_STATUS = E_PDU_STATUS(32850);
    pub const PDU_MODST_READY: E_PDU_STATUS = E_PDU_STATUS(32864);
    pub const PDU_MODST_NOT_READY: E_PDU_STATUS = E_PDU_STATUS(32865);
    pub const PDU_MODST_NOT_AVAIL: E_PDU_STATUS = E_PDU_STATUS(32866);
    pub const PDU_MODST_AVAIL: E_PDU_STATUS = E_PDU_STATUS(32867);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_STATUS(pub ::std::os::raw::c_uint);
pub use self::E_PDU_STATUS as T_PDU_STATUS;
impl E_PDU_INFO {
    pub const PDU_INFO_MODULE_LIST_CHG: E_PDU_INFO = E_PDU_INFO(32880);
    pub const PDU_INFO_RSC_LOCK_CHG: E_PDU_INFO = E_PDU_INFO(32881);
    pub const PDU_INFO_PHYS_COMPARAM_CHG: E_PDU_INFO = E_PDU_INFO(32882);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_INFO(pub ::std::os::raw::c_uint);
pub use self::E_PDU_INFO as T_PDU_INFO;
impl E_PDU_EVT_DATA {
    pub const PDU_EVT_DATA_AVAILABLE: E_PDU_EVT_DATA = E_PDU_EVT_DATA(2049);
    pub const PDU_EVT_DATA_LOST: E_PDU_EVT_DATA = E_PDU_EVT_DATA(2050);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_EVT_DATA(pub ::std::os::raw::c_uint);
pub use self::E_PDU_EVT_DATA as T_PDU_EVT_DATA;
pub const PDU_ID_UNDEF: UNUM32 = 4294967294;
pub const PDU_HANDLE_UNDEF: UNUM32 = 4294967295;
impl E_PDU_FILTER {
    pub const PDU_FLT_PASS: E_PDU_FILTER = E_PDU_FILTER(1);
    pub const PDU_FLT_BLOCK: E_PDU_FILTER = E_PDU_FILTER(2);
    pub const PDU_FLT_PASS_UUDT: E_PDU_FILTER = E_PDU_FILTER(17);
    pub const PDU_FLT_BLOCK_UUDT: E_PDU_FILTER = E_PDU_FILTER(18);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_FILTER(pub ::std::os::raw::c_uint);
pub use self::E_PDU_FILTER as T_PDU_FILTER;
impl E_PDU_QUEUE_MODE {
    pub const PDU_QUE_UNLIMITED: E_PDU_QUEUE_MODE = E_PDU_QUEUE_MODE(0);
    pub const PDU_QUE_LIMITED: E_PDU_QUEUE_MODE = E_PDU_QUEUE_MODE(1);
    pub const PDU_QUE_CIRCULAR: E_PDU_QUEUE_MODE = E_PDU_QUEUE_MODE(2);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_QUEUE_MODE(pub ::std::os::raw::c_uint);
pub use self::E_PDU_QUEUE_MODE as T_PDU_QUEUE_MODE;
impl E_PDU_ERROR {
    pub const PDU_STATUS_NOERROR: E_PDU_ERROR = E_PDU_ERROR(0);
    pub const PDU_ERR_FCT_FAILED: E_PDU_ERROR = E_PDU_ERROR(1);
    pub const PDU_ERR_RESERVED_1: E_PDU_ERROR = E_PDU_ERROR(16);
    pub const PDU_ERR_COMM_PC_TO_VCI_FAILED: E_PDU_ERROR = E_PDU_ERROR(17);
    pub const PDU_ERR_PDUAPI_NOT_CONSTRUCTED: E_PDU_ERROR = E_PDU_ERROR(32);
    pub const PDU_ERR_SHARING_VIOLATION: E_PDU_ERROR = E_PDU_ERROR(33);
    pub const PDU_ERR_RESOURCE_BUSY: E_PDU_ERROR = E_PDU_ERROR(48);
    pub const PDU_ERR_RESOURCE_TABLE_CHANGED: E_PDU_ERROR = E_PDU_ERROR(49);
    pub const PDU_ERR_RESOURCE_ERROR: E_PDU_ERROR = E_PDU_ERROR(50);
    pub const PDU_ERR_CLL_NOT_CONNECTED: E_PDU_ERROR = E_PDU_ERROR(64);
    pub const PDU_ERR_CLL_NOT_STARTED: E_PDU_ERROR = E_PDU_ERROR(65);
    pub const PDU_ERR_INVALID_PARAMETERS: E_PDU_ERROR = E_PDU_ERROR(80);
    pub const PDU_ERR_INVALID_HANDLE: E_PDU_ERROR = E_PDU_ERROR(96);
    pub const PDU_ERR_VALUE_NOT_SUPPORTED: E_PDU_ERROR = E_PDU_ERROR(97);
    pub const PDU_ERR_ID_NOT_SUPPORTED: E_PDU_ERROR = E_PDU_ERROR(98);
    pub const PDU_ERR_COMPARAM_NOT_SUPPORTED: E_PDU_ERROR = E_PDU_ERROR(99);
    pub const PDU_ERR_COMPARAM_LOCKED: E_PDU_ERROR = E_PDU_ERROR(100);
    pub const PDU_ERR_TX_QUEUE_FULL: E_PDU_ERROR = E_PDU_ERROR(112);
    pub const PDU_ERR_EVENT_QUEUE_EMPTY: E_PDU_ERROR = E_PDU_ERROR(113);
    pub const PDU_ERR_VOLTAGE_NOT_SUPPORTED: E_PDU_ERROR = E_PDU_ERROR(128);
    pub const PDU_ERR_MUX_RSC_NOT_SUPPORTED: E_PDU_ERROR = E_PDU_ERROR(129);
    pub const PDU_ERR_CABLE_UNKNOWN: E_PDU_ERROR = E_PDU_ERROR(130);
    pub const PDU_ERR_NO_CABLE_DETECTED: E_PDU_ERROR = E_PDU_ERROR(131);
    pub const PDU_ERR_CLL_CONNECTED: E_PDU_ERROR = E_PDU_ERROR(132);
    pub const PDU_ERR_TEMPPARAM_NOT_ALLOWED: E_PDU_ERROR = E_PDU_ERROR(144);
    pub const PDU_ERR_RSC_LOCKED: E_PDU_ERROR = E_PDU_ERROR(160);
    pub const PDU_ERR_RSC_LOCKED_BY_OTHER_CLL: E_PDU_ERROR = E_PDU_ERROR(161);
    pub const PDU_ERR_RSC_NOT_LOCKED: E_PDU_ERROR = E_PDU_ERROR(162);
    pub const PDU_ERR_MODULE_NOT_CONNECTED: E_PDU_ERROR = E_PDU_ERROR(163);
    pub const PDU_ERR_API_SW_OUT_OF_DATE: E_PDU_ERROR = E_PDU_ERROR(164);
    pub const PDU_ERR_MODULE_FW_OUT_OF_DATE: E_PDU_ERROR = E_PDU_ERROR(165);
    pub const PDU_ERR_PIN_NOT_CONNECTED: E_PDU_ERROR = E_PDU_ERROR(166);
    pub const PDU_ERR_IP_PROTOCOL_NOT_SUPPORTED: E_PDU_ERROR = E_PDU_ERROR(176);
    pub const PDU_ERR_DOIP_ROUTING_ACTIVATION_FAILED: E_PDU_ERROR = E_PDU_ERROR(177);
    pub const PDU_ERR_DOIP_ROUTING_ACTIVATION_AUTHENTICATION_FAILED: E_PDU_ERROR = E_PDU_ERROR(178);
    pub const PDU_ERR_DOIP_AMBIGUOUS_LOGICAL_ADDRESS: E_PDU_ERROR = E_PDU_ERROR(179);
    pub const PDU_ERR_DOIP_ROUTING_ACTIVATION_INVALID_SOURCE_ADDRESS: E_PDU_ERROR =
        E_PDU_ERROR(180);
    pub const PDU_ERR_DOIP_ROUTING_ACTIVATION_NO_DATA_SOCKET_AVAILABLE: E_PDU_ERROR =
        E_PDU_ERROR(181);
    pub const PDU_ERR_DOIP_ROUTING_ACTIVATION_SOURCE_ADDRESS_CHANGED: E_PDU_ERROR =
        E_PDU_ERROR(182);
    pub const PDU_ERR_DOIP_ROUTING_ACTIVATION_SOURCE_ADDRESS_IN_USE: E_PDU_ERROR = E_PDU_ERROR(183);
    pub const PDU_ERR_DOIP_ROUTING_ACTIVATION_CONFIRMATION_REJECTED: E_PDU_ERROR = E_PDU_ERROR(184);
    pub const PDU_ERR_DOIP_ROUTING_ACTIVATION_TYPE_UNSUPPORTED: E_PDU_ERROR = E_PDU_ERROR(185);
    pub const PDU_ERR_DOIP_ROUTING_ACTIVATION_RESPONSE_CODE_UNKNOWN: E_PDU_ERROR = E_PDU_ERROR(186);
    pub const PDU_ERR_DOIP_ROUTING_ACTIVATION_RESPONSE_TIMEOUT: E_PDU_ERROR = E_PDU_ERROR(187);
    pub const PDU_ERR_DOIP_RESPONSE_TIMEOUT: E_PDU_ERROR = E_PDU_ERROR(188);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_ERROR(pub ::std::os::raw::c_uint);
pub use self::E_PDU_ERROR as T_PDU_ERROR;
impl E_PDU_ERR_EVT {
    pub const PDU_ERR_EVT_NOERROR: E_PDU_ERR_EVT = E_PDU_ERR_EVT(0);
    pub const PDU_ERR_EVT_FRAME_STRUCT: E_PDU_ERR_EVT = E_PDU_ERR_EVT(256);
    pub const PDU_ERR_EVT_TX_ERROR: E_PDU_ERR_EVT = E_PDU_ERR_EVT(257);
    pub const PDU_ERR_EVT_TESTER_PRESENT_ERROR: E_PDU_ERR_EVT = E_PDU_ERR_EVT(258);
    pub const PDU_ERR_EVT_RSC_LOCKED: E_PDU_ERR_EVT = E_PDU_ERR_EVT(265);
    pub const PDU_ERR_EVT_RX_TIMEOUT: E_PDU_ERR_EVT = E_PDU_ERR_EVT(259);
    pub const PDU_ERR_EVT_RX_ERROR: E_PDU_ERR_EVT = E_PDU_ERR_EVT(260);
    pub const PDU_ERR_EVT_PROT_ERR: E_PDU_ERR_EVT = E_PDU_ERR_EVT(261);
    pub const PDU_ERR_EVT_LOST_COMM_TO_VCI: E_PDU_ERR_EVT = E_PDU_ERR_EVT(262);
    pub const PDU_ERR_EVT_VCI_HARDWARE_FAULT: E_PDU_ERR_EVT = E_PDU_ERR_EVT(263);
    pub const PDU_ERR_EVT_INIT_ERROR: E_PDU_ERR_EVT = E_PDU_ERR_EVT(264);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct E_PDU_ERR_EVT(pub ::std::os::raw::c_uint);
pub use self::E_PDU_ERR_EVT as T_PDU_ERR_EVT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_DATA_ITEM {
    pub ItemType: T_PDU_IT,
    pub pData: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_DATA_ITEM"][::std::mem::size_of::<PDU_DATA_ITEM>() - 16usize];
    ["Alignment of PDU_DATA_ITEM"][::std::mem::align_of::<PDU_DATA_ITEM>() - 8usize];
    ["Offset of field: PDU_DATA_ITEM::ItemType"]
        [::std::mem::offset_of!(PDU_DATA_ITEM, ItemType) - 0usize];
    ["Offset of field: PDU_DATA_ITEM::pData"]
        [::std::mem::offset_of!(PDU_DATA_ITEM, pData) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_PROG_VOLTAGE_DATA {
    pub ProgVoltage_mv: UNUM32,
    pub PinOnDLC: UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_PROG_VOLTAGE_DATA"]
        [::std::mem::size_of::<PDU_IO_PROG_VOLTAGE_DATA>() - 8usize];
    ["Alignment of PDU_IO_PROG_VOLTAGE_DATA"]
        [::std::mem::align_of::<PDU_IO_PROG_VOLTAGE_DATA>() - 4usize];
    ["Offset of field: PDU_IO_PROG_VOLTAGE_DATA::ProgVoltage_mv"]
        [::std::mem::offset_of!(PDU_IO_PROG_VOLTAGE_DATA, ProgVoltage_mv) - 0usize];
    ["Offset of field: PDU_IO_PROG_VOLTAGE_DATA::PinOnDLC"]
        [::std::mem::offset_of!(PDU_IO_PROG_VOLTAGE_DATA, PinOnDLC) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_BYTEARRAY_DATA {
    pub DataSize: UNUM32,
    pub pData: *mut UNUM8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_BYTEARRAY_DATA"][::std::mem::size_of::<PDU_IO_BYTEARRAY_DATA>() - 16usize];
    ["Alignment of PDU_IO_BYTEARRAY_DATA"]
        [::std::mem::align_of::<PDU_IO_BYTEARRAY_DATA>() - 8usize];
    ["Offset of field: PDU_IO_BYTEARRAY_DATA::DataSize"]
        [::std::mem::offset_of!(PDU_IO_BYTEARRAY_DATA, DataSize) - 0usize];
    ["Offset of field: PDU_IO_BYTEARRAY_DATA::pData"]
        [::std::mem::offset_of!(PDU_IO_BYTEARRAY_DATA, pData) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_FILTER_DATA {
    pub FilterType: T_PDU_FILTER,
    pub FilterNumber: UNUM32,
    pub FilterCompareSize: UNUM32,
    pub FilterMaskMessage: [UNUM8; 12usize],
    pub FilterPatternMessage: [UNUM8; 12usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_FILTER_DATA"][::std::mem::size_of::<PDU_IO_FILTER_DATA>() - 36usize];
    ["Alignment of PDU_IO_FILTER_DATA"][::std::mem::align_of::<PDU_IO_FILTER_DATA>() - 4usize];
    ["Offset of field: PDU_IO_FILTER_DATA::FilterType"]
        [::std::mem::offset_of!(PDU_IO_FILTER_DATA, FilterType) - 0usize];
    ["Offset of field: PDU_IO_FILTER_DATA::FilterNumber"]
        [::std::mem::offset_of!(PDU_IO_FILTER_DATA, FilterNumber) - 4usize];
    ["Offset of field: PDU_IO_FILTER_DATA::FilterCompareSize"]
        [::std::mem::offset_of!(PDU_IO_FILTER_DATA, FilterCompareSize) - 8usize];
    ["Offset of field: PDU_IO_FILTER_DATA::FilterMaskMessage"]
        [::std::mem::offset_of!(PDU_IO_FILTER_DATA, FilterMaskMessage) - 12usize];
    ["Offset of field: PDU_IO_FILTER_DATA::FilterPatternMessage"]
        [::std::mem::offset_of!(PDU_IO_FILTER_DATA, FilterPatternMessage) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_FILTER_LIST {
    pub NumFilterEntries: UNUM32,
    pub pFilterData: *mut PDU_IO_FILTER_DATA,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_FILTER_LIST"][::std::mem::size_of::<PDU_IO_FILTER_LIST>() - 16usize];
    ["Alignment of PDU_IO_FILTER_LIST"][::std::mem::align_of::<PDU_IO_FILTER_LIST>() - 8usize];
    ["Offset of field: PDU_IO_FILTER_LIST::NumFilterEntries"]
        [::std::mem::offset_of!(PDU_IO_FILTER_LIST, NumFilterEntries) - 0usize];
    ["Offset of field: PDU_IO_FILTER_LIST::pFilterData"]
        [::std::mem::offset_of!(PDU_IO_FILTER_LIST, pFilterData) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_EVENT_QUEUE_PROPERTY_DATA {
    pub QueueSize: UNUM32,
    pub QueueMode: T_PDU_QUEUE_MODE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_EVENT_QUEUE_PROPERTY_DATA"]
        [::std::mem::size_of::<PDU_IO_EVENT_QUEUE_PROPERTY_DATA>() - 8usize];
    ["Alignment of PDU_IO_EVENT_QUEUE_PROPERTY_DATA"]
        [::std::mem::align_of::<PDU_IO_EVENT_QUEUE_PROPERTY_DATA>() - 4usize];
    ["Offset of field: PDU_IO_EVENT_QUEUE_PROPERTY_DATA::QueueSize"]
        [::std::mem::offset_of!(PDU_IO_EVENT_QUEUE_PROPERTY_DATA, QueueSize) - 0usize];
    ["Offset of field: PDU_IO_EVENT_QUEUE_PROPERTY_DATA::QueueMode"]
        [::std::mem::offset_of!(PDU_IO_EVENT_QUEUE_PROPERTY_DATA, QueueMode) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IP_ADDR_INFO {
    pub IpVersion: UNUM32,
    pub pAddress: *mut UNUM8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IP_ADDR_INFO"][::std::mem::size_of::<PDU_IP_ADDR_INFO>() - 16usize];
    ["Alignment of PDU_IP_ADDR_INFO"][::std::mem::align_of::<PDU_IP_ADDR_INFO>() - 8usize];
    ["Offset of field: PDU_IP_ADDR_INFO::IpVersion"]
        [::std::mem::offset_of!(PDU_IP_ADDR_INFO, IpVersion) - 0usize];
    ["Offset of field: PDU_IP_ADDR_INFO::pAddress"]
        [::std::mem::offset_of!(PDU_IP_ADDR_INFO, pAddress) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_VEHICLE_ID_REQUEST {
    pub PreselectionMode: UNUM32,
    pub PreselectionValue: *mut CHAR8,
    pub CombinationMode: UNUM32,
    pub VehicleDiscoveryTime: UNUM32,
    pub NumDestinationAddresses: UNUM32,
    pub pDestinationAddresses: *mut PDU_IP_ADDR_INFO,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_VEHICLE_ID_REQUEST"]
        [::std::mem::size_of::<PDU_IO_VEHICLE_ID_REQUEST>() - 40usize];
    ["Alignment of PDU_IO_VEHICLE_ID_REQUEST"]
        [::std::mem::align_of::<PDU_IO_VEHICLE_ID_REQUEST>() - 8usize];
    ["Offset of field: PDU_IO_VEHICLE_ID_REQUEST::PreselectionMode"]
        [::std::mem::offset_of!(PDU_IO_VEHICLE_ID_REQUEST, PreselectionMode) - 0usize];
    ["Offset of field: PDU_IO_VEHICLE_ID_REQUEST::PreselectionValue"]
        [::std::mem::offset_of!(PDU_IO_VEHICLE_ID_REQUEST, PreselectionValue) - 8usize];
    ["Offset of field: PDU_IO_VEHICLE_ID_REQUEST::CombinationMode"]
        [::std::mem::offset_of!(PDU_IO_VEHICLE_ID_REQUEST, CombinationMode) - 16usize];
    ["Offset of field: PDU_IO_VEHICLE_ID_REQUEST::VehicleDiscoveryTime"]
        [::std::mem::offset_of!(PDU_IO_VEHICLE_ID_REQUEST, VehicleDiscoveryTime) - 20usize];
    ["Offset of field: PDU_IO_VEHICLE_ID_REQUEST::NumDestinationAddresses"]
        [::std::mem::offset_of!(PDU_IO_VEHICLE_ID_REQUEST, NumDestinationAddresses) - 24usize];
    ["Offset of field: PDU_IO_VEHICLE_ID_REQUEST::pDestinationAddresses"]
        [::std::mem::offset_of!(PDU_IO_VEHICLE_ID_REQUEST, pDestinationAddresses) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_ETH_SWITCH_STATE {
    pub EthernetSenseState: UNUM32,
    pub EthernetActPinNumber: UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_ETH_SWITCH_STATE"][::std::mem::size_of::<PDU_IO_ETH_SWITCH_STATE>() - 8usize];
    ["Alignment of PDU_IO_ETH_SWITCH_STATE"]
        [::std::mem::align_of::<PDU_IO_ETH_SWITCH_STATE>() - 4usize];
    ["Offset of field: PDU_IO_ETH_SWITCH_STATE::EthernetSenseState"]
        [::std::mem::offset_of!(PDU_IO_ETH_SWITCH_STATE, EthernetSenseState) - 0usize];
    ["Offset of field: PDU_IO_ETH_SWITCH_STATE::EthernetActPinNumber"]
        [::std::mem::offset_of!(PDU_IO_ETH_SWITCH_STATE, EthernetActPinNumber) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_RSC_STATUS_DATA {
    pub hMod: UNUM32,
    pub ResourceId: UNUM32,
    pub ResourceStatus: UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_RSC_STATUS_DATA"][::std::mem::size_of::<PDU_RSC_STATUS_DATA>() - 12usize];
    ["Alignment of PDU_RSC_STATUS_DATA"][::std::mem::align_of::<PDU_RSC_STATUS_DATA>() - 4usize];
    ["Offset of field: PDU_RSC_STATUS_DATA::hMod"]
        [::std::mem::offset_of!(PDU_RSC_STATUS_DATA, hMod) - 0usize];
    ["Offset of field: PDU_RSC_STATUS_DATA::ResourceId"]
        [::std::mem::offset_of!(PDU_RSC_STATUS_DATA, ResourceId) - 4usize];
    ["Offset of field: PDU_RSC_STATUS_DATA::ResourceStatus"]
        [::std::mem::offset_of!(PDU_RSC_STATUS_DATA, ResourceStatus) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_RSC_STATUS_ITEM {
    pub ItemType: T_PDU_IT,
    pub NumEntries: UNUM32,
    pub pResourceStatusData: *mut PDU_RSC_STATUS_DATA,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_RSC_STATUS_ITEM"][::std::mem::size_of::<PDU_RSC_STATUS_ITEM>() - 16usize];
    ["Alignment of PDU_RSC_STATUS_ITEM"][::std::mem::align_of::<PDU_RSC_STATUS_ITEM>() - 8usize];
    ["Offset of field: PDU_RSC_STATUS_ITEM::ItemType"]
        [::std::mem::offset_of!(PDU_RSC_STATUS_ITEM, ItemType) - 0usize];
    ["Offset of field: PDU_RSC_STATUS_ITEM::NumEntries"]
        [::std::mem::offset_of!(PDU_RSC_STATUS_ITEM, NumEntries) - 4usize];
    ["Offset of field: PDU_RSC_STATUS_ITEM::pResourceStatusData"]
        [::std::mem::offset_of!(PDU_RSC_STATUS_ITEM, pResourceStatusData) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_PARAM_ITEM {
    pub ItemType: T_PDU_IT,
    pub ComParamId: UNUM32,
    pub ComParamDataType: T_PDU_PT,
    pub ComParamClass: T_PDU_PC,
    pub pComParamData: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_PARAM_ITEM"][::std::mem::size_of::<PDU_PARAM_ITEM>() - 24usize];
    ["Alignment of PDU_PARAM_ITEM"][::std::mem::align_of::<PDU_PARAM_ITEM>() - 8usize];
    ["Offset of field: PDU_PARAM_ITEM::ItemType"]
        [::std::mem::offset_of!(PDU_PARAM_ITEM, ItemType) - 0usize];
    ["Offset of field: PDU_PARAM_ITEM::ComParamId"]
        [::std::mem::offset_of!(PDU_PARAM_ITEM, ComParamId) - 4usize];
    ["Offset of field: PDU_PARAM_ITEM::ComParamDataType"]
        [::std::mem::offset_of!(PDU_PARAM_ITEM, ComParamDataType) - 8usize];
    ["Offset of field: PDU_PARAM_ITEM::ComParamClass"]
        [::std::mem::offset_of!(PDU_PARAM_ITEM, ComParamClass) - 12usize];
    ["Offset of field: PDU_PARAM_ITEM::pComParamData"]
        [::std::mem::offset_of!(PDU_PARAM_ITEM, pComParamData) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_MODULE_DATA {
    pub ModuleTypeId: UNUM32,
    pub hMod: UNUM32,
    pub pVendorModuleName: *mut CHAR8,
    pub pVendorAdditionalInfo: *mut CHAR8,
    pub ModuleStatus: T_PDU_STATUS,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_MODULE_DATA"][::std::mem::size_of::<PDU_MODULE_DATA>() - 32usize];
    ["Alignment of PDU_MODULE_DATA"][::std::mem::align_of::<PDU_MODULE_DATA>() - 8usize];
    ["Offset of field: PDU_MODULE_DATA::ModuleTypeId"]
        [::std::mem::offset_of!(PDU_MODULE_DATA, ModuleTypeId) - 0usize];
    ["Offset of field: PDU_MODULE_DATA::hMod"]
        [::std::mem::offset_of!(PDU_MODULE_DATA, hMod) - 4usize];
    ["Offset of field: PDU_MODULE_DATA::pVendorModuleName"]
        [::std::mem::offset_of!(PDU_MODULE_DATA, pVendorModuleName) - 8usize];
    ["Offset of field: PDU_MODULE_DATA::pVendorAdditionalInfo"]
        [::std::mem::offset_of!(PDU_MODULE_DATA, pVendorAdditionalInfo) - 16usize];
    ["Offset of field: PDU_MODULE_DATA::ModuleStatus"]
        [::std::mem::offset_of!(PDU_MODULE_DATA, ModuleStatus) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_MODULE_ITEM {
    pub ItemType: T_PDU_IT,
    pub NumEntries: UNUM32,
    pub pModuleData: *mut PDU_MODULE_DATA,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_MODULE_ITEM"][::std::mem::size_of::<PDU_MODULE_ITEM>() - 16usize];
    ["Alignment of PDU_MODULE_ITEM"][::std::mem::align_of::<PDU_MODULE_ITEM>() - 8usize];
    ["Offset of field: PDU_MODULE_ITEM::ItemType"]
        [::std::mem::offset_of!(PDU_MODULE_ITEM, ItemType) - 0usize];
    ["Offset of field: PDU_MODULE_ITEM::NumEntries"]
        [::std::mem::offset_of!(PDU_MODULE_ITEM, NumEntries) - 4usize];
    ["Offset of field: PDU_MODULE_ITEM::pModuleData"]
        [::std::mem::offset_of!(PDU_MODULE_ITEM, pModuleData) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_RSC_ID_ITEM_DATA {
    pub hMod: UNUM32,
    pub NumIds: UNUM32,
    pub pResourceIdArray: *mut UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_RSC_ID_ITEM_DATA"][::std::mem::size_of::<PDU_RSC_ID_ITEM_DATA>() - 16usize];
    ["Alignment of PDU_RSC_ID_ITEM_DATA"][::std::mem::align_of::<PDU_RSC_ID_ITEM_DATA>() - 8usize];
    ["Offset of field: PDU_RSC_ID_ITEM_DATA::hMod"]
        [::std::mem::offset_of!(PDU_RSC_ID_ITEM_DATA, hMod) - 0usize];
    ["Offset of field: PDU_RSC_ID_ITEM_DATA::NumIds"]
        [::std::mem::offset_of!(PDU_RSC_ID_ITEM_DATA, NumIds) - 4usize];
    ["Offset of field: PDU_RSC_ID_ITEM_DATA::pResourceIdArray"]
        [::std::mem::offset_of!(PDU_RSC_ID_ITEM_DATA, pResourceIdArray) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_RSC_ID_ITEM {
    pub ItemType: T_PDU_IT,
    pub NumModules: UNUM32,
    pub pResourceIdDataArray: *mut PDU_RSC_ID_ITEM_DATA,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_RSC_ID_ITEM"][::std::mem::size_of::<PDU_RSC_ID_ITEM>() - 16usize];
    ["Alignment of PDU_RSC_ID_ITEM"][::std::mem::align_of::<PDU_RSC_ID_ITEM>() - 8usize];
    ["Offset of field: PDU_RSC_ID_ITEM::ItemType"]
        [::std::mem::offset_of!(PDU_RSC_ID_ITEM, ItemType) - 0usize];
    ["Offset of field: PDU_RSC_ID_ITEM::NumModules"]
        [::std::mem::offset_of!(PDU_RSC_ID_ITEM, NumModules) - 4usize];
    ["Offset of field: PDU_RSC_ID_ITEM::pResourceIdDataArray"]
        [::std::mem::offset_of!(PDU_RSC_ID_ITEM, pResourceIdDataArray) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_PIN_DATA {
    pub DLCPinNumber: UNUM32,
    pub DLCPinTypeId: UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_PIN_DATA"][::std::mem::size_of::<PDU_PIN_DATA>() - 8usize];
    ["Alignment of PDU_PIN_DATA"][::std::mem::align_of::<PDU_PIN_DATA>() - 4usize];
    ["Offset of field: PDU_PIN_DATA::DLCPinNumber"]
        [::std::mem::offset_of!(PDU_PIN_DATA, DLCPinNumber) - 0usize];
    ["Offset of field: PDU_PIN_DATA::DLCPinTypeId"]
        [::std::mem::offset_of!(PDU_PIN_DATA, DLCPinTypeId) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_RSC_DATA {
    pub BusTypeId: UNUM32,
    pub ProtocolId: UNUM32,
    pub NumPinData: UNUM32,
    pub pDLCPinData: *mut PDU_PIN_DATA,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_RSC_DATA"][::std::mem::size_of::<PDU_RSC_DATA>() - 24usize];
    ["Alignment of PDU_RSC_DATA"][::std::mem::align_of::<PDU_RSC_DATA>() - 8usize];
    ["Offset of field: PDU_RSC_DATA::BusTypeId"]
        [::std::mem::offset_of!(PDU_RSC_DATA, BusTypeId) - 0usize];
    ["Offset of field: PDU_RSC_DATA::ProtocolId"]
        [::std::mem::offset_of!(PDU_RSC_DATA, ProtocolId) - 4usize];
    ["Offset of field: PDU_RSC_DATA::NumPinData"]
        [::std::mem::offset_of!(PDU_RSC_DATA, NumPinData) - 8usize];
    ["Offset of field: PDU_RSC_DATA::pDLCPinData"]
        [::std::mem::offset_of!(PDU_RSC_DATA, pDLCPinData) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_RSC_CONFLICT_DATA {
    pub hMod: UNUM32,
    pub ResourceId: UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_RSC_CONFLICT_DATA"][::std::mem::size_of::<PDU_RSC_CONFLICT_DATA>() - 8usize];
    ["Alignment of PDU_RSC_CONFLICT_DATA"]
        [::std::mem::align_of::<PDU_RSC_CONFLICT_DATA>() - 4usize];
    ["Offset of field: PDU_RSC_CONFLICT_DATA::hMod"]
        [::std::mem::offset_of!(PDU_RSC_CONFLICT_DATA, hMod) - 0usize];
    ["Offset of field: PDU_RSC_CONFLICT_DATA::ResourceId"]
        [::std::mem::offset_of!(PDU_RSC_CONFLICT_DATA, ResourceId) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_RSC_CONFLICT_ITEM {
    pub ItemType: T_PDU_IT,
    pub NumEntries: UNUM32,
    pub pRscConflictData: *mut PDU_RSC_CONFLICT_DATA,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_RSC_CONFLICT_ITEM"][::std::mem::size_of::<PDU_RSC_CONFLICT_ITEM>() - 16usize];
    ["Alignment of PDU_RSC_CONFLICT_ITEM"]
        [::std::mem::align_of::<PDU_RSC_CONFLICT_ITEM>() - 8usize];
    ["Offset of field: PDU_RSC_CONFLICT_ITEM::ItemType"]
        [::std::mem::offset_of!(PDU_RSC_CONFLICT_ITEM, ItemType) - 0usize];
    ["Offset of field: PDU_RSC_CONFLICT_ITEM::NumEntries"]
        [::std::mem::offset_of!(PDU_RSC_CONFLICT_ITEM, NumEntries) - 4usize];
    ["Offset of field: PDU_RSC_CONFLICT_ITEM::pRscConflictData"]
        [::std::mem::offset_of!(PDU_RSC_CONFLICT_ITEM, pRscConflictData) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_ECU_UNIQUE_RESP_DATA {
    pub UniqueRespIdentifier: UNUM32,
    pub NumParamItems: UNUM32,
    pub pParams: *mut PDU_PARAM_ITEM,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_ECU_UNIQUE_RESP_DATA"]
        [::std::mem::size_of::<PDU_ECU_UNIQUE_RESP_DATA>() - 16usize];
    ["Alignment of PDU_ECU_UNIQUE_RESP_DATA"]
        [::std::mem::align_of::<PDU_ECU_UNIQUE_RESP_DATA>() - 8usize];
    ["Offset of field: PDU_ECU_UNIQUE_RESP_DATA::UniqueRespIdentifier"]
        [::std::mem::offset_of!(PDU_ECU_UNIQUE_RESP_DATA, UniqueRespIdentifier) - 0usize];
    ["Offset of field: PDU_ECU_UNIQUE_RESP_DATA::NumParamItems"]
        [::std::mem::offset_of!(PDU_ECU_UNIQUE_RESP_DATA, NumParamItems) - 4usize];
    ["Offset of field: PDU_ECU_UNIQUE_RESP_DATA::pParams"]
        [::std::mem::offset_of!(PDU_ECU_UNIQUE_RESP_DATA, pParams) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_UNIQUE_RESP_ID_TABLE_ITEM {
    pub ItemType: T_PDU_IT,
    pub NumEntries: UNUM32,
    pub pUniqueData: *mut PDU_ECU_UNIQUE_RESP_DATA,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_UNIQUE_RESP_ID_TABLE_ITEM"]
        [::std::mem::size_of::<PDU_UNIQUE_RESP_ID_TABLE_ITEM>() - 16usize];
    ["Alignment of PDU_UNIQUE_RESP_ID_TABLE_ITEM"]
        [::std::mem::align_of::<PDU_UNIQUE_RESP_ID_TABLE_ITEM>() - 8usize];
    ["Offset of field: PDU_UNIQUE_RESP_ID_TABLE_ITEM::ItemType"]
        [::std::mem::offset_of!(PDU_UNIQUE_RESP_ID_TABLE_ITEM, ItemType) - 0usize];
    ["Offset of field: PDU_UNIQUE_RESP_ID_TABLE_ITEM::NumEntries"]
        [::std::mem::offset_of!(PDU_UNIQUE_RESP_ID_TABLE_ITEM, NumEntries) - 4usize];
    ["Offset of field: PDU_UNIQUE_RESP_ID_TABLE_ITEM::pUniqueData"]
        [::std::mem::offset_of!(PDU_UNIQUE_RESP_ID_TABLE_ITEM, pUniqueData) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_EVENT_ITEM {
    pub ItemType: T_PDU_IT,
    pub hCop: UNUM32,
    pub pCoPTag: *mut ::std::os::raw::c_void,
    pub Timestamp: UNUM32,
    pub pData: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_EVENT_ITEM"][::std::mem::size_of::<PDU_EVENT_ITEM>() - 32usize];
    ["Alignment of PDU_EVENT_ITEM"][::std::mem::align_of::<PDU_EVENT_ITEM>() - 8usize];
    ["Offset of field: PDU_EVENT_ITEM::ItemType"]
        [::std::mem::offset_of!(PDU_EVENT_ITEM, ItemType) - 0usize];
    ["Offset of field: PDU_EVENT_ITEM::hCop"]
        [::std::mem::offset_of!(PDU_EVENT_ITEM, hCop) - 4usize];
    ["Offset of field: PDU_EVENT_ITEM::pCoPTag"]
        [::std::mem::offset_of!(PDU_EVENT_ITEM, pCoPTag) - 8usize];
    ["Offset of field: PDU_EVENT_ITEM::Timestamp"]
        [::std::mem::offset_of!(PDU_EVENT_ITEM, Timestamp) - 16usize];
    ["Offset of field: PDU_EVENT_ITEM::pData"]
        [::std::mem::offset_of!(PDU_EVENT_ITEM, pData) - 24usize];
};
pub use self::T_PDU_STATUS as PDU_STATUS_DATA;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_INFO_DATA {
    pub InfoCode: T_PDU_INFO,
    pub ExtraInfoData: UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_INFO_DATA"][::std::mem::size_of::<PDU_INFO_DATA>() - 8usize];
    ["Alignment of PDU_INFO_DATA"][::std::mem::align_of::<PDU_INFO_DATA>() - 4usize];
    ["Offset of field: PDU_INFO_DATA::InfoCode"]
        [::std::mem::offset_of!(PDU_INFO_DATA, InfoCode) - 0usize];
    ["Offset of field: PDU_INFO_DATA::ExtraInfoData"]
        [::std::mem::offset_of!(PDU_INFO_DATA, ExtraInfoData) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_ERROR_DATA {
    pub ErrorCodeId: T_PDU_ERR_EVT,
    pub ExtraErrorInfoId: UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_ERROR_DATA"][::std::mem::size_of::<PDU_ERROR_DATA>() - 8usize];
    ["Alignment of PDU_ERROR_DATA"][::std::mem::align_of::<PDU_ERROR_DATA>() - 4usize];
    ["Offset of field: PDU_ERROR_DATA::ErrorCodeId"]
        [::std::mem::offset_of!(PDU_ERROR_DATA, ErrorCodeId) - 0usize];
    ["Offset of field: PDU_ERROR_DATA::ExtraErrorInfoId"]
        [::std::mem::offset_of!(PDU_ERROR_DATA, ExtraErrorInfoId) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_FLAG_DATA {
    pub NumFlagBytes: UNUM32,
    pub pFlagData: *mut UNUM8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_FLAG_DATA"][::std::mem::size_of::<PDU_FLAG_DATA>() - 16usize];
    ["Alignment of PDU_FLAG_DATA"][::std::mem::align_of::<PDU_FLAG_DATA>() - 8usize];
    ["Offset of field: PDU_FLAG_DATA::NumFlagBytes"]
        [::std::mem::offset_of!(PDU_FLAG_DATA, NumFlagBytes) - 0usize];
    ["Offset of field: PDU_FLAG_DATA::pFlagData"]
        [::std::mem::offset_of!(PDU_FLAG_DATA, pFlagData) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_EXTRA_INFO {
    pub NumHeaderBytes: UNUM32,
    pub NumFooterBytes: UNUM32,
    pub pHeaderBytes: *mut UNUM8,
    pub pFooterBytes: *mut UNUM8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_EXTRA_INFO"][::std::mem::size_of::<PDU_EXTRA_INFO>() - 24usize];
    ["Alignment of PDU_EXTRA_INFO"][::std::mem::align_of::<PDU_EXTRA_INFO>() - 8usize];
    ["Offset of field: PDU_EXTRA_INFO::NumHeaderBytes"]
        [::std::mem::offset_of!(PDU_EXTRA_INFO, NumHeaderBytes) - 0usize];
    ["Offset of field: PDU_EXTRA_INFO::NumFooterBytes"]
        [::std::mem::offset_of!(PDU_EXTRA_INFO, NumFooterBytes) - 4usize];
    ["Offset of field: PDU_EXTRA_INFO::pHeaderBytes"]
        [::std::mem::offset_of!(PDU_EXTRA_INFO, pHeaderBytes) - 8usize];
    ["Offset of field: PDU_EXTRA_INFO::pFooterBytes"]
        [::std::mem::offset_of!(PDU_EXTRA_INFO, pFooterBytes) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_RESULT_DATA {
    pub RxFlag: PDU_FLAG_DATA,
    pub UniqueRespIdentifier: UNUM32,
    pub AcceptanceId: UNUM32,
    pub TimestampFlags: PDU_FLAG_DATA,
    pub TxMsgDoneTimestamp: UNUM32,
    pub StartMsgTimestamp: UNUM32,
    pub pExtraInfo: *mut PDU_EXTRA_INFO,
    pub NumDataBytes: UNUM32,
    pub pDataBytes: *mut UNUM8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_RESULT_DATA"][::std::mem::size_of::<PDU_RESULT_DATA>() - 72usize];
    ["Alignment of PDU_RESULT_DATA"][::std::mem::align_of::<PDU_RESULT_DATA>() - 8usize];
    ["Offset of field: PDU_RESULT_DATA::RxFlag"]
        [::std::mem::offset_of!(PDU_RESULT_DATA, RxFlag) - 0usize];
    ["Offset of field: PDU_RESULT_DATA::UniqueRespIdentifier"]
        [::std::mem::offset_of!(PDU_RESULT_DATA, UniqueRespIdentifier) - 16usize];
    ["Offset of field: PDU_RESULT_DATA::AcceptanceId"]
        [::std::mem::offset_of!(PDU_RESULT_DATA, AcceptanceId) - 20usize];
    ["Offset of field: PDU_RESULT_DATA::TimestampFlags"]
        [::std::mem::offset_of!(PDU_RESULT_DATA, TimestampFlags) - 24usize];
    ["Offset of field: PDU_RESULT_DATA::TxMsgDoneTimestamp"]
        [::std::mem::offset_of!(PDU_RESULT_DATA, TxMsgDoneTimestamp) - 40usize];
    ["Offset of field: PDU_RESULT_DATA::StartMsgTimestamp"]
        [::std::mem::offset_of!(PDU_RESULT_DATA, StartMsgTimestamp) - 44usize];
    ["Offset of field: PDU_RESULT_DATA::pExtraInfo"]
        [::std::mem::offset_of!(PDU_RESULT_DATA, pExtraInfo) - 48usize];
    ["Offset of field: PDU_RESULT_DATA::NumDataBytes"]
        [::std::mem::offset_of!(PDU_RESULT_DATA, NumDataBytes) - 56usize];
    ["Offset of field: PDU_RESULT_DATA::pDataBytes"]
        [::std::mem::offset_of!(PDU_RESULT_DATA, pDataBytes) - 64usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_VERSION_DATA {
    pub MVCI_Part1StandardVersion: UNUM32,
    pub MVCI_Part2StandardVersion: UNUM32,
    pub HwSerialNumber: UNUM32,
    pub HwName: [CHAR8; 64usize],
    pub HwVersion: UNUM32,
    pub HwDate: UNUM32,
    pub HwInterface: UNUM32,
    pub FwName: [CHAR8; 64usize],
    pub FwVersion: UNUM32,
    pub FwDate: UNUM32,
    pub VendorName: [CHAR8; 64usize],
    pub PDUApiSwName: [CHAR8; 64usize],
    pub PDUApiSwVersion: UNUM32,
    pub PDUApiSwDate: UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_VERSION_DATA"][::std::mem::size_of::<PDU_VERSION_DATA>() - 296usize];
    ["Alignment of PDU_VERSION_DATA"][::std::mem::align_of::<PDU_VERSION_DATA>() - 4usize];
    ["Offset of field: PDU_VERSION_DATA::MVCI_Part1StandardVersion"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, MVCI_Part1StandardVersion) - 0usize];
    ["Offset of field: PDU_VERSION_DATA::MVCI_Part2StandardVersion"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, MVCI_Part2StandardVersion) - 4usize];
    ["Offset of field: PDU_VERSION_DATA::HwSerialNumber"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, HwSerialNumber) - 8usize];
    ["Offset of field: PDU_VERSION_DATA::HwName"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, HwName) - 12usize];
    ["Offset of field: PDU_VERSION_DATA::HwVersion"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, HwVersion) - 76usize];
    ["Offset of field: PDU_VERSION_DATA::HwDate"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, HwDate) - 80usize];
    ["Offset of field: PDU_VERSION_DATA::HwInterface"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, HwInterface) - 84usize];
    ["Offset of field: PDU_VERSION_DATA::FwName"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, FwName) - 88usize];
    ["Offset of field: PDU_VERSION_DATA::FwVersion"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, FwVersion) - 152usize];
    ["Offset of field: PDU_VERSION_DATA::FwDate"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, FwDate) - 156usize];
    ["Offset of field: PDU_VERSION_DATA::VendorName"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, VendorName) - 160usize];
    ["Offset of field: PDU_VERSION_DATA::PDUApiSwName"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, PDUApiSwName) - 224usize];
    ["Offset of field: PDU_VERSION_DATA::PDUApiSwVersion"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, PDUApiSwVersion) - 288usize];
    ["Offset of field: PDU_VERSION_DATA::PDUApiSwDate"]
        [::std::mem::offset_of!(PDU_VERSION_DATA, PDUApiSwDate) - 292usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_EXP_RESP_DATA {
    pub ResponseType: UNUM32,
    pub AcceptanceId: UNUM32,
    pub NumMaskPatternBytes: UNUM32,
    pub pMaskData: *mut UNUM8,
    pub pPatternData: *mut UNUM8,
    pub NumUniqueRespIds: UNUM32,
    pub pUniqueRespIds: *mut UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_EXP_RESP_DATA"][::std::mem::size_of::<PDU_EXP_RESP_DATA>() - 48usize];
    ["Alignment of PDU_EXP_RESP_DATA"][::std::mem::align_of::<PDU_EXP_RESP_DATA>() - 8usize];
    ["Offset of field: PDU_EXP_RESP_DATA::ResponseType"]
        [::std::mem::offset_of!(PDU_EXP_RESP_DATA, ResponseType) - 0usize];
    ["Offset of field: PDU_EXP_RESP_DATA::AcceptanceId"]
        [::std::mem::offset_of!(PDU_EXP_RESP_DATA, AcceptanceId) - 4usize];
    ["Offset of field: PDU_EXP_RESP_DATA::NumMaskPatternBytes"]
        [::std::mem::offset_of!(PDU_EXP_RESP_DATA, NumMaskPatternBytes) - 8usize];
    ["Offset of field: PDU_EXP_RESP_DATA::pMaskData"]
        [::std::mem::offset_of!(PDU_EXP_RESP_DATA, pMaskData) - 16usize];
    ["Offset of field: PDU_EXP_RESP_DATA::pPatternData"]
        [::std::mem::offset_of!(PDU_EXP_RESP_DATA, pPatternData) - 24usize];
    ["Offset of field: PDU_EXP_RESP_DATA::NumUniqueRespIds"]
        [::std::mem::offset_of!(PDU_EXP_RESP_DATA, NumUniqueRespIds) - 32usize];
    ["Offset of field: PDU_EXP_RESP_DATA::pUniqueRespIds"]
        [::std::mem::offset_of!(PDU_EXP_RESP_DATA, pUniqueRespIds) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_COP_CTRL_DATA {
    pub Time: UNUM32,
    pub NumSendCycles: SNUM32,
    pub NumReceiveCycles: SNUM32,
    pub TempParamUpdate: UNUM32,
    pub TxFlag: PDU_FLAG_DATA,
    pub NumPossibleExpectedResponses: UNUM32,
    pub pExpectedResponseArray: *mut PDU_EXP_RESP_DATA,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_COP_CTRL_DATA"][::std::mem::size_of::<PDU_COP_CTRL_DATA>() - 48usize];
    ["Alignment of PDU_COP_CTRL_DATA"][::std::mem::align_of::<PDU_COP_CTRL_DATA>() - 8usize];
    ["Offset of field: PDU_COP_CTRL_DATA::Time"]
        [::std::mem::offset_of!(PDU_COP_CTRL_DATA, Time) - 0usize];
    ["Offset of field: PDU_COP_CTRL_DATA::NumSendCycles"]
        [::std::mem::offset_of!(PDU_COP_CTRL_DATA, NumSendCycles) - 4usize];
    ["Offset of field: PDU_COP_CTRL_DATA::NumReceiveCycles"]
        [::std::mem::offset_of!(PDU_COP_CTRL_DATA, NumReceiveCycles) - 8usize];
    ["Offset of field: PDU_COP_CTRL_DATA::TempParamUpdate"]
        [::std::mem::offset_of!(PDU_COP_CTRL_DATA, TempParamUpdate) - 12usize];
    ["Offset of field: PDU_COP_CTRL_DATA::TxFlag"]
        [::std::mem::offset_of!(PDU_COP_CTRL_DATA, TxFlag) - 16usize];
    ["Offset of field: PDU_COP_CTRL_DATA::NumPossibleExpectedResponses"]
        [::std::mem::offset_of!(PDU_COP_CTRL_DATA, NumPossibleExpectedResponses) - 32usize];
    ["Offset of field: PDU_COP_CTRL_DATA::pExpectedResponseArray"]
        [::std::mem::offset_of!(PDU_COP_CTRL_DATA, pExpectedResponseArray) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_ENTITY_ADDRESS_DATA {
    pub LogicalAddress: UNUM32,
    pub DoIPCtrlTimeout: UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_ENTITY_ADDRESS_DATA"]
        [::std::mem::size_of::<PDU_IO_ENTITY_ADDRESS_DATA>() - 8usize];
    ["Alignment of PDU_IO_ENTITY_ADDRESS_DATA"]
        [::std::mem::align_of::<PDU_IO_ENTITY_ADDRESS_DATA>() - 4usize];
    ["Offset of field: PDU_IO_ENTITY_ADDRESS_DATA::LogicalAddress"]
        [::std::mem::offset_of!(PDU_IO_ENTITY_ADDRESS_DATA, LogicalAddress) - 0usize];
    ["Offset of field: PDU_IO_ENTITY_ADDRESS_DATA::DoIPCtrlTimeout"]
        [::std::mem::offset_of!(PDU_IO_ENTITY_ADDRESS_DATA, DoIPCtrlTimeout) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_ENTITY_STATUS_DATA {
    pub EntityType: UNUM32,
    pub TcpClientsMax: UNUM32,
    pub TcpClients: UNUM32,
    pub MaxDataSize: UNUM32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_ENTITY_STATUS_DATA"]
        [::std::mem::size_of::<PDU_IO_ENTITY_STATUS_DATA>() - 16usize];
    ["Alignment of PDU_IO_ENTITY_STATUS_DATA"]
        [::std::mem::align_of::<PDU_IO_ENTITY_STATUS_DATA>() - 4usize];
    ["Offset of field: PDU_IO_ENTITY_STATUS_DATA::EntityType"]
        [::std::mem::offset_of!(PDU_IO_ENTITY_STATUS_DATA, EntityType) - 0usize];
    ["Offset of field: PDU_IO_ENTITY_STATUS_DATA::TcpClientsMax"]
        [::std::mem::offset_of!(PDU_IO_ENTITY_STATUS_DATA, TcpClientsMax) - 4usize];
    ["Offset of field: PDU_IO_ENTITY_STATUS_DATA::TcpClients"]
        [::std::mem::offset_of!(PDU_IO_ENTITY_STATUS_DATA, TcpClients) - 8usize];
    ["Offset of field: PDU_IO_ENTITY_STATUS_DATA::MaxDataSize"]
        [::std::mem::offset_of!(PDU_IO_ENTITY_STATUS_DATA, MaxDataSize) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_ITEM {
    pub ItemType: T_PDU_IT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_ITEM"][::std::mem::size_of::<PDU_ITEM>() - 4usize];
    ["Alignment of PDU_ITEM"][::std::mem::align_of::<PDU_ITEM>() - 4usize];
    ["Offset of field: PDU_ITEM::ItemType"][::std::mem::offset_of!(PDU_ITEM, ItemType) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_TLS_CERT_DATA {
    pub CertLen: UNUM32,
    pub CertBuffer: *mut UNUM8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_TLS_CERT_DATA"][::std::mem::size_of::<PDU_IO_TLS_CERT_DATA>() - 16usize];
    ["Alignment of PDU_IO_TLS_CERT_DATA"][::std::mem::align_of::<PDU_IO_TLS_CERT_DATA>() - 8usize];
    ["Offset of field: PDU_IO_TLS_CERT_DATA::CertLen"]
        [::std::mem::offset_of!(PDU_IO_TLS_CERT_DATA, CertLen) - 0usize];
    ["Offset of field: PDU_IO_TLS_CERT_DATA::CertBuffer"]
        [::std::mem::offset_of!(PDU_IO_TLS_CERT_DATA, CertBuffer) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_TLS_CERT_CHAIN_DATA {
    pub NumCertificates: UNUM32,
    pub pTlsCertData: *mut PDU_IO_TLS_CERT_DATA,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_TLS_CERT_CHAIN_DATA"]
        [::std::mem::size_of::<PDU_IO_TLS_CERT_CHAIN_DATA>() - 16usize];
    ["Alignment of PDU_IO_TLS_CERT_CHAIN_DATA"]
        [::std::mem::align_of::<PDU_IO_TLS_CERT_CHAIN_DATA>() - 8usize];
    ["Offset of field: PDU_IO_TLS_CERT_CHAIN_DATA::NumCertificates"]
        [::std::mem::offset_of!(PDU_IO_TLS_CERT_CHAIN_DATA, NumCertificates) - 0usize];
    ["Offset of field: PDU_IO_TLS_CERT_CHAIN_DATA::pTlsCertData"]
        [::std::mem::offset_of!(PDU_IO_TLS_CERT_CHAIN_DATA, pTlsCertData) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PDU_IO_TLS_CERTIFICATE {
    pub NumCertChains: UNUM32,
    pub pTlsCertChainData: *mut PDU_IO_TLS_CERT_CHAIN_DATA,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PDU_IO_TLS_CERTIFICATE"][::std::mem::size_of::<PDU_IO_TLS_CERTIFICATE>() - 16usize];
    ["Alignment of PDU_IO_TLS_CERTIFICATE"]
        [::std::mem::align_of::<PDU_IO_TLS_CERTIFICATE>() - 8usize];
    ["Offset of field: PDU_IO_TLS_CERTIFICATE::NumCertChains"]
        [::std::mem::offset_of!(PDU_IO_TLS_CERTIFICATE, NumCertChains) - 0usize];
    ["Offset of field: PDU_IO_TLS_CERTIFICATE::pTlsCertChainData"]
        [::std::mem::offset_of!(PDU_IO_TLS_CERTIFICATE, pTlsCertChainData) - 8usize];
};
pub type CALLBACKFNC = ::std::option::Option<
    unsafe extern "C" fn(
        eventType: T_PDU_EVT_DATA,
        hMod: UNUM32,
        hCLL: UNUM32,
        pCllTag: *mut ::std::os::raw::c_void,
        pAPITag: *mut ::std::os::raw::c_void,
    ),
>;
pub struct DPduApiSys {
    __library: ::libloading::Library,
    pub PDUConstruct: unsafe extern "C" fn(
        OptionStr: *mut CHAR8,
        pAPITag: *mut ::std::os::raw::c_void,
    ) -> T_PDU_ERROR,
    pub PDUDestruct: unsafe extern "C" fn() -> T_PDU_ERROR,
    pub PDUIoCtl: unsafe extern "C" fn(
        hMod: UNUM32,
        hCLL: UNUM32,
        IoCtlCommandId: UNUM32,
        pInputData: *mut PDU_DATA_ITEM,
        pOutputData: *mut *mut PDU_DATA_ITEM,
    ) -> T_PDU_ERROR,
    pub PDUGetVersion:
        unsafe extern "C" fn(hMod: UNUM32, pVersionData: *mut PDU_VERSION_DATA) -> T_PDU_ERROR,
    pub PDUGetStatus: unsafe extern "C" fn(
        hMod: UNUM32,
        hCLL: UNUM32,
        hCoP: UNUM32,
        pStatusCode: *mut T_PDU_STATUS,
        pTimestamp: *mut UNUM32,
        pExtraInfo: *mut UNUM32,
    ) -> T_PDU_ERROR,
    pub PDUGetLastError: unsafe extern "C" fn(
        hMod: UNUM32,
        hCLL: UNUM32,
        pErrorCode: *mut T_PDU_ERR_EVT,
        phCoP: *mut UNUM32,
        pTimestamp: *mut UNUM32,
        pExtraErrorInfo: *mut UNUM32,
    ) -> T_PDU_ERROR,
    pub PDUGetResourceStatus:
        unsafe extern "C" fn(pResourceStatus: *mut PDU_RSC_STATUS_ITEM) -> T_PDU_ERROR,
    pub PDUCreateComLogicalLink: unsafe extern "C" fn(
        hMod: UNUM32,
        pRscData: *mut PDU_RSC_DATA,
        resourceId: UNUM32,
        pCllTag: *mut ::std::os::raw::c_void,
        phCLL: *mut UNUM32,
        pCllCreateFlag: *mut PDU_FLAG_DATA,
    ) -> T_PDU_ERROR,
    pub PDUDestroyComLogicalLink: unsafe extern "C" fn(hMod: UNUM32, hCLL: UNUM32) -> T_PDU_ERROR,
    pub PDUConnect: unsafe extern "C" fn(hMod: UNUM32, hCLL: UNUM32) -> T_PDU_ERROR,
    pub PDUDisconnect: unsafe extern "C" fn(hMod: UNUM32, hCLL: UNUM32) -> T_PDU_ERROR,
    pub PDULockResource:
        unsafe extern "C" fn(hMod: UNUM32, hCLL: UNUM32, LockMask: UNUM32) -> T_PDU_ERROR,
    pub PDUUnlockResource:
        unsafe extern "C" fn(hMod: UNUM32, hCLL: UNUM32, LockMask: UNUM32) -> T_PDU_ERROR,
    pub PDUGetComParam: unsafe extern "C" fn(
        hMod: UNUM32,
        hCLL: UNUM32,
        ParamId: UNUM32,
        pParamItem: *mut *mut PDU_PARAM_ITEM,
    ) -> T_PDU_ERROR,
    pub PDUSetComParam: unsafe extern "C" fn(
        hMod: UNUM32,
        hCLL: UNUM32,
        pParamItem: *mut PDU_PARAM_ITEM,
    ) -> T_PDU_ERROR,
    pub PDUStartComPrimitive: unsafe extern "C" fn(
        hMod: UNUM32,
        hCLL: UNUM32,
        CoPType: T_PDU_COPT,
        CoPDataSize: UNUM32,
        pCoPData: *mut UNUM8,
        pCopCtrlData: *mut PDU_COP_CTRL_DATA,
        pCoPTag: *mut ::std::os::raw::c_void,
        phCoP: *mut UNUM32,
    ) -> T_PDU_ERROR,
    pub PDUCancelComPrimitive:
        unsafe extern "C" fn(hMod: UNUM32, hCLL: UNUM32, hCoP: UNUM32) -> T_PDU_ERROR,
    pub PDUGetEventItem: unsafe extern "C" fn(
        hMod: UNUM32,
        hCLL: UNUM32,
        pEventItem: *mut *mut PDU_EVENT_ITEM,
    ) -> T_PDU_ERROR,
    pub PDUDestroyItem: unsafe extern "C" fn(pItem: *mut PDU_ITEM) -> T_PDU_ERROR,
    pub PDURegisterEventCallback: unsafe extern "C" fn(
        hMod: UNUM32,
        hCLL: UNUM32,
        EventCallbackFunction: CALLBACKFNC,
    ) -> T_PDU_ERROR,
    pub PDUGetObjectId: unsafe extern "C" fn(
        pduObjectType: T_PDU_OBJT,
        pShortname: *mut CHAR8,
        pPduObjectId: *mut UNUM32,
    ) -> T_PDU_ERROR,
    pub PDUGetModuleIds:
        unsafe extern "C" fn(pModuleIdList: *mut *mut PDU_MODULE_ITEM) -> T_PDU_ERROR,
    pub PDUGetResourceIds: unsafe extern "C" fn(
        hMod: UNUM32,
        pResourceIdData: *mut PDU_RSC_DATA,
        pResourceIdList: *mut *mut PDU_RSC_ID_ITEM,
    ) -> T_PDU_ERROR,
    pub PDUGetConflictingResources: unsafe extern "C" fn(
        resourceId: UNUM32,
        pInputModuleList: *mut PDU_MODULE_ITEM,
        pOutputConflictList: *mut *mut PDU_RSC_CONFLICT_ITEM,
    ) -> T_PDU_ERROR,
    pub PDUGetUniqueRespIdTable: unsafe extern "C" fn(
        hMod: UNUM32,
        hCLL: UNUM32,
        pUniqueRespIdTable: *mut *mut PDU_UNIQUE_RESP_ID_TABLE_ITEM,
    ) -> T_PDU_ERROR,
    pub PDUSetUniqueRespIdTable: unsafe extern "C" fn(
        hMod: UNUM32,
        hCLL: UNUM32,
        pUniqueRespIdTable: *mut PDU_UNIQUE_RESP_ID_TABLE_ITEM,
    ) -> T_PDU_ERROR,
    pub PDUModuleConnect: unsafe extern "C" fn(hMod: UNUM32) -> T_PDU_ERROR,
    pub PDUModuleDisconnect: unsafe extern "C" fn(hMod: UNUM32) -> T_PDU_ERROR,
    pub PDUGetTimestamp: unsafe extern "C" fn(hMod: UNUM32, pTimestamp: *mut UNUM32) -> T_PDU_ERROR,
}
impl DPduApiSys {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let library = ::libloading::Library::new(path)?;
        Self::from_library(library)
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let PDUConstruct = __library.get(b"PDUConstruct\0").map(|sym| *sym)?;
        let PDUDestruct = __library.get(b"PDUDestruct\0").map(|sym| *sym)?;
        let PDUIoCtl = __library.get(b"PDUIoCtl\0").map(|sym| *sym)?;
        let PDUGetVersion = __library.get(b"PDUGetVersion\0").map(|sym| *sym)?;
        let PDUGetStatus = __library.get(b"PDUGetStatus\0").map(|sym| *sym)?;
        let PDUGetLastError = __library.get(b"PDUGetLastError\0").map(|sym| *sym)?;
        let PDUGetResourceStatus = __library.get(b"PDUGetResourceStatus\0").map(|sym| *sym)?;
        let PDUCreateComLogicalLink = __library
            .get(b"PDUCreateComLogicalLink\0")
            .map(|sym| *sym)?;
        let PDUDestroyComLogicalLink = __library
            .get(b"PDUDestroyComLogicalLink\0")
            .map(|sym| *sym)?;
        let PDUConnect = __library.get(b"PDUConnect\0").map(|sym| *sym)?;
        let PDUDisconnect = __library.get(b"PDUDisconnect\0").map(|sym| *sym)?;
        let PDULockResource = __library.get(b"PDULockResource\0").map(|sym| *sym)?;
        let PDUUnlockResource = __library.get(b"PDUUnlockResource\0").map(|sym| *sym)?;
        let PDUGetComParam = __library.get(b"PDUGetComParam\0").map(|sym| *sym)?;
        let PDUSetComParam = __library.get(b"PDUSetComParam\0").map(|sym| *sym)?;
        let PDUStartComPrimitive = __library.get(b"PDUStartComPrimitive\0").map(|sym| *sym)?;
        let PDUCancelComPrimitive = __library.get(b"PDUCancelComPrimitive\0").map(|sym| *sym)?;
        let PDUGetEventItem = __library.get(b"PDUGetEventItem\0").map(|sym| *sym)?;
        let PDUDestroyItem = __library.get(b"PDUDestroyItem\0").map(|sym| *sym)?;
        let PDURegisterEventCallback = __library
            .get(b"PDURegisterEventCallback\0")
            .map(|sym| *sym)?;
        let PDUGetObjectId = __library.get(b"PDUGetObjectId\0").map(|sym| *sym)?;
        let PDUGetModuleIds = __library.get(b"PDUGetModuleIds\0").map(|sym| *sym)?;
        let PDUGetResourceIds = __library.get(b"PDUGetResourceIds\0").map(|sym| *sym)?;
        let PDUGetConflictingResources = __library
            .get(b"PDUGetConflictingResources\0")
            .map(|sym| *sym)?;
        let PDUGetUniqueRespIdTable = __library
            .get(b"PDUGetUniqueRespIdTable\0")
            .map(|sym| *sym)?;
        let PDUSetUniqueRespIdTable = __library
            .get(b"PDUSetUniqueRespIdTable\0")
            .map(|sym| *sym)?;
        let PDUModuleConnect = __library.get(b"PDUModuleConnect\0").map(|sym| *sym)?;
        let PDUModuleDisconnect = __library.get(b"PDUModuleDisconnect\0").map(|sym| *sym)?;
        let PDUGetTimestamp = __library.get(b"PDUGetTimestamp\0").map(|sym| *sym)?;
        Ok(DPduApiSys {
            __library,
            PDUConstruct,
            PDUDestruct,
            PDUIoCtl,
            PDUGetVersion,
            PDUGetStatus,
            PDUGetLastError,
            PDUGetResourceStatus,
            PDUCreateComLogicalLink,
            PDUDestroyComLogicalLink,
            PDUConnect,
            PDUDisconnect,
            PDULockResource,
            PDUUnlockResource,
            PDUGetComParam,
            PDUSetComParam,
            PDUStartComPrimitive,
            PDUCancelComPrimitive,
            PDUGetEventItem,
            PDUDestroyItem,
            PDURegisterEventCallback,
            PDUGetObjectId,
            PDUGetModuleIds,
            PDUGetResourceIds,
            PDUGetConflictingResources,
            PDUGetUniqueRespIdTable,
            PDUSetUniqueRespIdTable,
            PDUModuleConnect,
            PDUModuleDisconnect,
            PDUGetTimestamp,
        })
    }
    pub unsafe fn PDUConstruct(
        &self,
        OptionStr: *mut CHAR8,
        pAPITag: *mut ::std::os::raw::c_void,
    ) -> T_PDU_ERROR {
        (self.PDUConstruct)(OptionStr, pAPITag)
    }
    pub unsafe fn PDUDestruct(&self) -> T_PDU_ERROR {
        (self.PDUDestruct)()
    }
    pub unsafe fn PDUIoCtl(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        IoCtlCommandId: UNUM32,
        pInputData: *mut PDU_DATA_ITEM,
        pOutputData: *mut *mut PDU_DATA_ITEM,
    ) -> T_PDU_ERROR {
        (self.PDUIoCtl)(hMod, hCLL, IoCtlCommandId, pInputData, pOutputData)
    }
    pub unsafe fn PDUGetVersion(
        &self,
        hMod: UNUM32,
        pVersionData: *mut PDU_VERSION_DATA,
    ) -> T_PDU_ERROR {
        (self.PDUGetVersion)(hMod, pVersionData)
    }
    pub unsafe fn PDUGetStatus(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        hCoP: UNUM32,
        pStatusCode: *mut T_PDU_STATUS,
        pTimestamp: *mut UNUM32,
        pExtraInfo: *mut UNUM32,
    ) -> T_PDU_ERROR {
        (self.PDUGetStatus)(hMod, hCLL, hCoP, pStatusCode, pTimestamp, pExtraInfo)
    }
    pub unsafe fn PDUGetLastError(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        pErrorCode: *mut T_PDU_ERR_EVT,
        phCoP: *mut UNUM32,
        pTimestamp: *mut UNUM32,
        pExtraErrorInfo: *mut UNUM32,
    ) -> T_PDU_ERROR {
        (self.PDUGetLastError)(hMod, hCLL, pErrorCode, phCoP, pTimestamp, pExtraErrorInfo)
    }
    pub unsafe fn PDUGetResourceStatus(
        &self,
        pResourceStatus: *mut PDU_RSC_STATUS_ITEM,
    ) -> T_PDU_ERROR {
        (self.PDUGetResourceStatus)(pResourceStatus)
    }
    pub unsafe fn PDUCreateComLogicalLink(
        &self,
        hMod: UNUM32,
        pRscData: *mut PDU_RSC_DATA,
        resourceId: UNUM32,
        pCllTag: *mut ::std::os::raw::c_void,
        phCLL: *mut UNUM32,
        pCllCreateFlag: *mut PDU_FLAG_DATA,
    ) -> T_PDU_ERROR {
        (self.PDUCreateComLogicalLink)(hMod, pRscData, resourceId, pCllTag, phCLL, pCllCreateFlag)
    }
    pub unsafe fn PDUDestroyComLogicalLink(&self, hMod: UNUM32, hCLL: UNUM32) -> T_PDU_ERROR {
        (self.PDUDestroyComLogicalLink)(hMod, hCLL)
    }
    pub unsafe fn PDUConnect(&self, hMod: UNUM32, hCLL: UNUM32) -> T_PDU_ERROR {
        (self.PDUConnect)(hMod, hCLL)
    }
    pub unsafe fn PDUDisconnect(&self, hMod: UNUM32, hCLL: UNUM32) -> T_PDU_ERROR {
        (self.PDUDisconnect)(hMod, hCLL)
    }
    pub unsafe fn PDULockResource(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        LockMask: UNUM32,
    ) -> T_PDU_ERROR {
        (self.PDULockResource)(hMod, hCLL, LockMask)
    }
    pub unsafe fn PDUUnlockResource(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        LockMask: UNUM32,
    ) -> T_PDU_ERROR {
        (self.PDUUnlockResource)(hMod, hCLL, LockMask)
    }
    pub unsafe fn PDUGetComParam(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        ParamId: UNUM32,
        pParamItem: *mut *mut PDU_PARAM_ITEM,
    ) -> T_PDU_ERROR {
        (self.PDUGetComParam)(hMod, hCLL, ParamId, pParamItem)
    }
    pub unsafe fn PDUSetComParam(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        pParamItem: *mut PDU_PARAM_ITEM,
    ) -> T_PDU_ERROR {
        (self.PDUSetComParam)(hMod, hCLL, pParamItem)
    }
    pub unsafe fn PDUStartComPrimitive(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        CoPType: T_PDU_COPT,
        CoPDataSize: UNUM32,
        pCoPData: *mut UNUM8,
        pCopCtrlData: *mut PDU_COP_CTRL_DATA,
        pCoPTag: *mut ::std::os::raw::c_void,
        phCoP: *mut UNUM32,
    ) -> T_PDU_ERROR {
        (self.PDUStartComPrimitive)(
            hMod,
            hCLL,
            CoPType,
            CoPDataSize,
            pCoPData,
            pCopCtrlData,
            pCoPTag,
            phCoP,
        )
    }
    pub unsafe fn PDUCancelComPrimitive(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        hCoP: UNUM32,
    ) -> T_PDU_ERROR {
        (self.PDUCancelComPrimitive)(hMod, hCLL, hCoP)
    }
    pub unsafe fn PDUGetEventItem(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        pEventItem: *mut *mut PDU_EVENT_ITEM,
    ) -> T_PDU_ERROR {
        (self.PDUGetEventItem)(hMod, hCLL, pEventItem)
    }
    pub unsafe fn PDUDestroyItem(&self, pItem: *mut PDU_ITEM) -> T_PDU_ERROR {
        (self.PDUDestroyItem)(pItem)
    }
    pub unsafe fn PDURegisterEventCallback(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        EventCallbackFunction: CALLBACKFNC,
    ) -> T_PDU_ERROR {
        (self.PDURegisterEventCallback)(hMod, hCLL, EventCallbackFunction)
    }
    pub unsafe fn PDUGetObjectId(
        &self,
        pduObjectType: T_PDU_OBJT,
        pShortname: *mut CHAR8,
        pPduObjectId: *mut UNUM32,
    ) -> T_PDU_ERROR {
        (self.PDUGetObjectId)(pduObjectType, pShortname, pPduObjectId)
    }
    pub unsafe fn PDUGetModuleIds(&self, pModuleIdList: *mut *mut PDU_MODULE_ITEM) -> T_PDU_ERROR {
        (self.PDUGetModuleIds)(pModuleIdList)
    }
    pub unsafe fn PDUGetResourceIds(
        &self,
        hMod: UNUM32,
        pResourceIdData: *mut PDU_RSC_DATA,
        pResourceIdList: *mut *mut PDU_RSC_ID_ITEM,
    ) -> T_PDU_ERROR {
        (self.PDUGetResourceIds)(hMod, pResourceIdData, pResourceIdList)
    }
    pub unsafe fn PDUGetConflictingResources(
        &self,
        resourceId: UNUM32,
        pInputModuleList: *mut PDU_MODULE_ITEM,
        pOutputConflictList: *mut *mut PDU_RSC_CONFLICT_ITEM,
    ) -> T_PDU_ERROR {
        (self.PDUGetConflictingResources)(resourceId, pInputModuleList, pOutputConflictList)
    }
    pub unsafe fn PDUGetUniqueRespIdTable(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        pUniqueRespIdTable: *mut *mut PDU_UNIQUE_RESP_ID_TABLE_ITEM,
    ) -> T_PDU_ERROR {
        (self.PDUGetUniqueRespIdTable)(hMod, hCLL, pUniqueRespIdTable)
    }
    pub unsafe fn PDUSetUniqueRespIdTable(
        &self,
        hMod: UNUM32,
        hCLL: UNUM32,
        pUniqueRespIdTable: *mut PDU_UNIQUE_RESP_ID_TABLE_ITEM,
    ) -> T_PDU_ERROR {
        (self.PDUSetUniqueRespIdTable)(hMod, hCLL, pUniqueRespIdTable)
    }
    pub unsafe fn PDUModuleConnect(&self, hMod: UNUM32) -> T_PDU_ERROR {
        (self.PDUModuleConnect)(hMod)
    }
    pub unsafe fn PDUModuleDisconnect(&self, hMod: UNUM32) -> T_PDU_ERROR {
        (self.PDUModuleDisconnect)(hMod)
    }
    pub unsafe fn PDUGetTimestamp(&self, hMod: UNUM32, pTimestamp: *mut UNUM32) -> T_PDU_ERROR {
        (self.PDUGetTimestamp)(hMod, pTimestamp)
    }
}
